spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raw_news
    driver-class-name : com.mysql.cj.jdbc.Driver
    username: root
    password: ASdf123!
  mvc:
    servlet:
      load-on-startup: 1
  jpa:
    database : mysql
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
server:
  port: 8081


naver :
  client:
    iD: e2MFfyjofCQtFyJ70P8I
    secret: 3tsQ5Irie_
  base:
    url: https://openapi.naver.com/v1/search/news.json
    path: /v1/search/news.json
